"use strict";

const { SlashCommandBuilder } = require('discord.js');
const { EmbedBuilder } = require('discord.js');
const fs = require('node:fs');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('listmusic')
		.setDescription('Lists music lists and contents of lists')
		.addStringOption(option =>
			option.setName('listname')
				.setDescription('Leave blank to list all lists of music, otherwise specify list to list contents')),

	async execute(interaction) {
		const musicListContents = interaction.options.getString('listname')
		const musicLists = fs.readdirSync('music');
		var itemToList = ''

		if (musicLists.includes(musicListContents)) {
			itemToList = fs.readdirSync(`music/${musicListContents}`)
			itemToList = itemToList.join('\n')
		} else {
			itemToList = musicLists.join('\n') 
		}

		let embed = new EmbedBuilder()
			.setColor(0x0099FF)
			.addFields(
				{ name: 'Music Lists', value: itemToList},
			)
			.setTimestamp()
			.setFooter({ text: 'Generated by DMBot' });

		await interaction.reply({ embeds: [embed] });
	},
};
